# Homework

In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import make_blobs

In [6]:
x,y=make_blobs()
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=5,test_size=0.2)

In [7]:
from scipy.stats import norm

class NaiveBayes():        
        
        def fit(self,x,y):
            self.classes=np.unique(y)
            self.mean=np.zeros((len(self.classes),x.shape[1]))
            self.std=np.zeros((len(self.classes),x.shape[1]))
            self.priors=np.zeros(len(self.classes))
            for i,n in enumerate(self.classes):
                cl_x=x[y==n]
                self.mean[i,:]=cl_x.mean(axis=0)
                self.std[i,:]=cl_x.std(axis=0)
                self.priors[i]=cl_x.shape[0]/x.shape[0]
            
    
        def predict(self,x):
            prob=np.zeros((x.shape[0],len(self.classes)))
        
            for i ,n in enumerate(self.classes):
                log_prob=np.log(self.priors[i])
                liklehod=self.pdf(x,self.mean[i],self.std[i])
                prob[:,i]=liklehod+log_prob
        
            return np.argmax(prob, axis=1)
        
        
        
        def pdf(self,x,mean,std):
            return np.sum(np.log(norm.pdf(x,mean,std)),axis=1)
            
        
model=NaiveBayes()
model.fit(xtrain,ytrain)
prediction=model.predict(xtest)

prediction 

array([2, 0, 1, 1, 2, 0, 1, 0, 0, 2, 2, 1, 1, 2, 0, 1, 2, 0, 2, 0],
      dtype=int64)

In [8]:
class LineardiscriminantAnalysis:
    def fit(self, x, y):
        mean_0 = np.mean(x[y == 0], axis=0)
        mean_1 = np.mean(x[y == 1], axis=0)
        cov0 = np.cov(x[y == 0],rowvar=False)
        cov1 = np.cov(x[y == 1],rowvar=False)
        covar_matr = ((x[y==0].shape[0]-1)*cov0 + (x[y==1].shape[0]-1)*cov1)/((x[y==0].shape[0]-1)+(x[y==1].shape[0]-1))
        prior0=x[y==0].shape[0]/y.shape[0]
        prior1=x[y==1].shape[0]/y.shape[0]
        self.w = np.linalg.inv(covar_matr).dot(mean_1 - mean_0)
        self.b = ((mean_0.dot(self.w) + mean_1.dot(self.w)) / 2)+np.log(prior1/prior0)
        
    def predict(self, xtest):
        prediction = np.sign(xtest.dot(self.w) + self.b)
        prediction[prediction!=1]=0
        return prediction
    
    


In [9]:
x,y=make_blobs(centers=2,cluster_std=1)

In [10]:


xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=0,test_size=0.2)

In [11]:
model=LineardiscriminantAnalysis()
model.fit(xtrain,ytrain)

In [12]:
model.predict(xtrain
             )

array([1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.])

In [13]:
ytrain

array([1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1])

In [15]:
from sklearn.decomposition import PCA

In [16]:
from sklearn.datasets import make_blobs



In [17]:
x,y=make_blobs(n_samples=100,n_features=10,centers=2,cluster_std=10)

In [18]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=5,test_size=0.3)

In [19]:
disc_mod=LineardiscriminantAnalysis()
disc_mod.fit(xtrain,ytrain)
prediction=disc_mod.predict(xtest)
accuracy_score(prediction,ytest)

0.8666666666666667